In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
# Load College Scorecard Field of Study data
scorecard_fos = pd.read_csv(r"..\data\raw\Most-Recent-Cohorts-Field-of-Study.csv")
#scorecard_fos = pd.read_csv(C:\Users\sigep\OneDrive\Documents\My Repos\capstone_da16_python\data\raw")
# Load College Scorecard Institution Level data
scorecard_il = pd.read_csv(r"..\data\raw\Most-Recent-Cohorts-Institution.csv")

C:\Users\sigep\AppData\Local\Temp\ipykernel_25408\1375951179.py:5: DtypeWarning: Columns (9,1407,1408,1431,1432,1532,1537,1538,1539,1540,1542,1546,1589,1601,1602,1606,1608,1611,1614,1615,1616,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1653,1679,1690,1692,1697,1700,1702,1725,1726,1727,1728,1729,1743,1815,1816,1817,1818,1823,1824,1830,1831,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1909,1910,1911,1912,1913,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1983,1984,2376,2377,2403,2404,2495,2496,2497,2498,2499,2500,2501,2502,2503,2504,2505,2506,2507,2508,2509,2510,2511,2512,2513,2514,2515,2516,2517,2518,2519,2520,2521,2522,2523,2524,2525,2526,2527,2528,2529,2530,2958,3215,3231,3235,3236) have mixed types. Specify dtype option on import or set low_memory=False.
  scorecard_il = pd.read_csv(r"..\data\raw\Most-Recent-Cohorts-Institution.csv")

In [3]:
[col for col in scorecard_il.columns if "cost" in col.lower()]

['COSTT4_A', 'COSTT4_P', 'MDCOST_PD', 'MDCOST_ALL']

In [4]:
scorecard_il.columns.tolist()

['UNITID',
 'OPEID',
 'OPEID6',
 'INSTNM',
 'CITY',
 'STABBR',
 'ZIP',
 'ACCREDAGENCY',
 'INSTURL',
 'NPCURL',
 'SCH_DEG',
 'HCM2',
 'MAIN',
 'NUMBRANCH',
 'PREDDEG',
 'HIGHDEG',
 'CONTROL',
 'ST_FIPS',
 'REGION',
 'LOCALE',
 'LOCALE2',
 'LATITUDE',
 'LONGITUDE',
 'CCBASIC',
 'CCUGPROF',
 'CCSIZSET',
 'HBCU',
 'PBI',
 'ANNHI',
 'TRIBAL',
 'AANAPII',
 'HSI',
 'NANTI',
 'MENONLY',
 'WOMENONLY',
 'RELAFFIL',
 'ADM_RATE',
 'ADM_RATE_ALL',
 'SATVR25',
 'SATVR75',
 'SATMT25',
 'SATMT75',
 'SATWR25',
 'SATWR75',
 'SATVRMID',
 'SATMTMID',
 'SATWRMID',
 'ACTCM25',
 'ACTCM75',
 'ACTEN25',
 'ACTEN75',
 'ACTMT25',
 'ACTMT75',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'PCIP12',
 'PCIP13',
 'PCIP14',
 'PCIP15',
 'PCIP16',
 'PCIP19',
 'PCIP22',
 'PCIP23',
 'PCIP24',
 'PCIP25',
 'PCIP26',
 'PCIP27',
 'PCIP29',
 'PCIP30',
 'PCIP31',
 'PCIP38',
 'PCIP39',
 'PCIP40',
 'PCIP41',
 'PCIP42',
 'PCIP43',
 'PCIP44',
 'PCIP45',
 'PCIP46',
 'PCIP47',
 'PCIP48',
 'PCIP49',
 'PCIP50',
 'PCIP51',
 'PCIP52',
 'PCIP54',
 'CIP01CERT1',
 'CIP01CERT2',
 'CIP01ASSOC',
 'CIP01CERT4',
 'CIP01BACHL',
 'CIP03CERT1',
 'CIP03CERT2',
 'CIP03ASSOC',
 'CIP03CERT4',
 'CIP03BACHL',
 'CIP04CERT1',
 'CIP04CERT2',
 'CIP04ASSOC',
 'CIP04CERT4',
 'CIP04BACHL',
 'CIP05CERT1',
 'CIP05CERT2',
 'CIP05ASSOC',
 'CIP05CERT4',
 'CIP05BACHL',
 'CIP09CERT1',
 'CIP09CERT2',
 'CIP09ASSOC',
 'CIP09CERT4',
 'CIP09BACHL',
 'CIP10CERT1',
 'CIP10CERT2',
 'CIP10ASSOC',
 'CIP10CERT4',
 'CIP10BACHL',
 'CIP11CERT1',
 'CIP11CERT2',
 'CIP11ASSOC',
 'CIP11CERT4',
 'CIP11BACHL',
 'CIP12CERT1',
 'CIP12CERT2',
 'CIP12ASSOC',
 'CIP12CERT4',
 'CIP12BACHL',
 'CIP13CERT1',
 'CIP13CERT2',
 'CIP13ASSOC',
 'CIP13CERT4',
 'CIP13BACHL',
 'CIP14CERT1',
 'CIP14CERT2',
 'CIP14ASSOC',
 'CIP14CERT4',
 'CIP14BACHL',
 'CIP15CERT1',
 'CIP15CERT2',
 'CIP15ASSOC',
 'CIP15CERT4',
 'CIP15BACHL',
 'CIP16CERT1',
 'CIP16CERT2',
 'CIP16ASSOC',
 'CIP16CERT4',
 'CIP16BACHL',
 'CIP19CERT1',
 'CIP19CERT2',
 'CIP19ASSOC',
 'CIP19CERT4',
 'CIP19BACHL',
 'CIP22CERT1',
 'CIP22CERT2',
 'CIP22ASSOC',
 'CIP22CERT4',
 'CIP22BACHL',
 'CIP23CERT1',
 'CIP23CERT2',
 'CIP23ASSOC',
 'CIP23CERT4',
 'CIP23BACHL',
 'CIP24CERT1',
 'CIP24CERT2',
 'CIP24ASSOC',
 'CIP24CERT4',
 'CIP24BACHL',
 'CIP25CERT1',
 'CIP25CERT2',
 'CIP25ASSOC',
 'CIP25CERT4',
 'CIP25BACHL',
 'CIP26CERT1',
 'CIP26CERT2',
 'CIP26ASSOC',
 'CIP26CERT4',
 'CIP26BACHL',
 'CIP27CERT1',
 'CIP27CERT2',
 'CIP27ASSOC',
 'CIP27CERT4',
 'CIP27BACHL',
 'CIP29CERT1',
 'CIP29CERT2',
 'CIP29ASSOC',
 'CIP29CERT4',
 'CIP29BACHL',
 'CIP30CERT1',
 'CIP30CERT2',
 'CIP30ASSOC',
 'CIP30CERT4',
 'CIP30BACHL',
 'CIP31CERT1',
 'CIP31CERT2',
 'CIP31ASSOC',
 'CIP31CERT4',
 'CIP31BACHL',
 'CIP38CERT1',
 'CIP38CERT2',
 'CIP38ASSOC',
 'CIP38CERT4',
 'CIP38BACHL',
 'CIP39CERT1',
 'CIP39CERT2',
 'CIP39ASSOC',
 'CIP39CERT4',
 'CIP39BACHL',
 'CIP40CERT1',
 'CIP40CERT2',
 'CIP40ASSOC',
 'CIP40CERT4',
 'CIP40BACHL',
 'CIP41CERT1',
 'CIP41CERT2',
 'CIP41ASSOC',
 'CIP41CERT4',
 'CIP41BACHL',
 'CIP42CERT1',
 'CIP42CERT2',
 'CIP42ASSOC',
 'CIP42CERT4',
 'CIP42BACHL',
 'CIP43CERT1',
 'CIP43CERT2',
 'CIP43ASSOC',
 'CIP43CERT4',
 'CIP43BACHL',
 'CIP44CERT1',
 'CIP44CERT2',
 'CIP44ASSOC',
 'CIP44CERT4',
 'CIP44BACHL',
 'CIP45CERT1',
 'CIP45CERT2',
 'CIP45ASSOC',
 'CIP45CERT4',
 'CIP45BACHL',
 'CIP46CERT1',
 'CIP46CERT2',
 'CIP46ASSOC',
 'CIP46CERT4',
 'CIP46BACHL',
 'CIP47CERT1',
 'CIP47CERT2',
 'CIP47ASSOC',
 'CIP47CERT4',
 'CIP47BACHL',
 'CIP48CERT1',
 'CIP48CERT2',
 'CIP48ASSOC',
 'CIP48CERT4',
 'CIP48BACHL',
 'CIP49CERT1',
 'CIP49CERT2',
 'CIP49ASSOC',
 'CIP49CERT4',
 'CIP49BACHL',
 'CIP50CERT1',
 'CIP50CERT2',
 'CIP50ASSOC',
 'CIP50CERT4',
 'CIP50BACHL',
 'CIP51CERT1',
 'CIP51CERT2',
 'CIP51ASSOC',
 'CIP51CERT4',
 'CIP51BACHL',
 'CIP52CERT1',
 'CIP52CERT2',
 'CIP52ASSOC',
 'CIP52CERT4',
 'CIP52BACHL',
 'CIP54CERT1',
 'CIP54CERT2',
 'CIP54ASSOC',
 'CIP54CERT4',
 'CIP54BACHL',
 'DISTANCEONLY',
 'UGDS',
 'UG',
 'UGDS_WHITE',
 'UGDS_BLACK',
 'UGDS_HISP',
 'UGDS_ASIAN',
 'UGDS_AIAN',
 'UGDS_NHPI',
 'UGDS_2MOR',
 'UGDS_NRA',
 'UGDS_UNKN',
 'UGDS_WHITENH',
 'UGDS_BLACKNH',
 'UGDS_API',
 'UGDS_AIANOLD',
 'UGDS_HISPOLD',
 'UG_NRA',
 'UG_UNKN',
 'UG_WHITENH',
 'UG_BLACKNH',
 'UG_API',
 'UG_AIANOLD',
 'UG_HISPOLD',
 'PPTUG_EF',
 'PPTUG_EF2',
 'CURROPER',
 'NPT4_PUB',
 'NPT4_PRIV',
 'NPT4_PROG',
 'NPT4_OTHER',
 'NPT41_PUB',
 'NPT42_PUB',
 'NPT43_PUB',
 'NPT44_PUB',
 'NPT45_PUB',
 'NPT41_PRIV',
 'NPT42_PRIV',
 'NPT43_PRIV',
 'NPT44_PRIV',
 'NPT45_PRIV',
 'NPT41_PROG',
 'NPT42_PROG',
 'NPT43_PROG',
 'NPT44_PROG',
 'NPT45_PROG',
 'NPT41_OTHER',
 'NPT42_OTHER',
 'NPT43_OTHER',
 'NPT44_OTHER',
 'NPT45_OTHER',
 'NPT4_048_PUB',
 'NPT4_048_PRIV',
 'NPT4_048_PROG',
 'NPT4_048_OTHER',
 'NPT4_3075_PUB',
 'NPT4_3075_PRIV',
 'NPT4_75UP_PUB',
 'NPT4_75UP_PRIV',
 'NPT4_3075_PROG',
 'NPT4_3075_OTHER',
 'NPT4_75UP_PROG',
 'NPT4_75UP_OTHER',
 'NUM4_PUB',
 'NUM4_PRIV',
 'NUM4_PROG',
 'NUM4_OTHER',
 'NUM41_PUB',
 'NUM42_PUB',
 'NUM43_PUB',
 'NUM44_PUB',
 'NUM45_PUB',
 'NUM41_PRIV',
 'NUM42_PRIV',
 'NUM43_PRIV',
 'NUM44_PRIV',
 'NUM45_PRIV',
 'NUM41_PROG',
 'NUM42_PROG',
 'NUM43_PROG',
 'NUM44_PROG',
 'NUM45_PROG',
 'NUM41_OTHER',
 'NUM42_OTHER',
 'NUM43_OTHER',
 'NUM44_OTHER',
 'NUM45_OTHER',
 'COSTT4_A',
 'COSTT4_P',
 'TUITIONFEE_IN',
 'TUITIONFEE_OUT',
 'TUITIONFEE_PROG',
 'TUITFTE',
 'INEXPFTE',
 'AVGFACSAL',
 'PFTFAC',
 'PCTPELL',
 'C150_4',
 'C150_L4',
 'C150_4_POOLED',
 'C150_L4_POOLED',
 'POOLYRS',
 'PFTFTUG1_EF',
 'D150_4',
 'D150_L4',
 'D150_4_POOLED',
 'D150_L4_POOLED',
 'C150_4_WHITE',
 'C150_4_BLACK',
 'C150_4_HISP',
 'C150_4_ASIAN',
 'C150_4_AIAN',
 'C150_4_NHPI',
 'C150_4_2MOR',
 'C150_4_NRA',
 'C150_4_UNKN',
 'C150_4_WHITENH',
 'C150_4_BLACKNH',
 'C150_4_API',
 'C150_4_AIANOLD',
 'C150_4_HISPOLD',
 'C150_L4_WHITE',
 'C150_L4_BLACK',
 'C150_L4_HISP',
 'C150_L4_ASIAN',
 'C150_L4_AIAN',
 'C150_L4_NHPI',
 'C150_L4_2MOR',
 'C150_L4_NRA',
 'C150_L4_UNKN',
 'C150_L4_WHITENH',
 'C150_L4_BLACKNH',
 'C150_L4_API',
 'C150_L4_AIANOLD',
 'C150_L4_HISPOLD',
 'C200_4',
 'C200_L4',
 'D200_4',
 'D200_L4',
 'RET_FT4',
 'RET_FTL4',
 'RET_PT4',
 'RET_PTL4',
 'C200_4_POOLED',
 'C200_L4_POOLED',
 'POOLYRS200',
 'D200_4_POOLED',
 'D200_L4_POOLED',
 'PCTFLOAN',
 'UG25ABV',
 'CDR2',
 'CDR3',
 'DEATH_YR2_RT',
 'COMP_ORIG_YR2_RT',
 'COMP_4YR_TRANS_YR2_RT',
 'COMP_2YR_TRANS_YR2_RT',
 'WDRAW_ORIG_YR2_RT',
 'WDRAW_4YR_TRANS_YR2_RT',
 'WDRAW_2YR_TRANS_YR2_RT',
 'ENRL_ORIG_YR2_RT',
 'ENRL_4YR_TRANS_YR2_RT',
 'ENRL_2YR_TRANS_YR2_RT',
 'UNKN_ORIG_YR2_RT',
 'UNKN_4YR_TRANS_YR2_RT',
 'UNKN_2YR_TRANS_YR2_RT',
 'LO_INC_DEATH_YR2_RT',
 'LO_INC_COMP_ORIG_YR2_RT',
 'LO_INC_COMP_4YR_TRANS_YR2_RT',
 'LO_INC_COMP_2YR_TRANS_YR2_RT',
 'LO_INC_WDRAW_ORIG_YR2_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR2_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR2_RT',
 'LO_INC_ENRL_ORIG_YR2_RT',
 'LO_INC_ENRL_4YR_TRANS_YR2_RT',
 'LO_INC_ENRL_2YR_TRANS_YR2_RT',
 'LO_INC_UNKN_ORIG_YR2_RT',
 'LO_INC_UNKN_4YR_TRANS_YR2_RT',
 'LO_INC_UNKN_2YR_TRANS_YR2_RT',
 'MD_INC_DEATH_YR2_RT',
 'MD_INC_COMP_ORIG_YR2_RT',
 'MD_INC_COMP_4YR_TRANS_YR2_RT',
 'MD_INC_COMP_2YR_TRANS_YR2_RT',
 'MD_INC_WDRAW_ORIG_YR2_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR2_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR2_RT',
 'MD_INC_ENRL_ORIG_YR2_RT',
 'MD_INC_ENRL_4YR_TRANS_YR2_RT',
 'MD_INC_ENRL_2YR_TRANS_YR2_RT',
 'MD_INC_UNKN_ORIG_YR2_RT',
 'MD_INC_UNKN_4YR_TRANS_YR2_RT',
 'MD_INC_UNKN_2YR_TRANS_YR2_RT',
 'HI_INC_DEATH_YR2_RT',
 'HI_INC_COMP_ORIG_YR2_RT',
 'HI_INC_COMP_4YR_TRANS_YR2_RT',
 'HI_INC_COMP_2YR_TRANS_YR2_RT',
 'HI_INC_WDRAW_ORIG_YR2_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR2_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR2_RT',
 'HI_INC_ENRL_ORIG_YR2_RT',
 'HI_INC_ENRL_4YR_TRANS_YR2_RT',
 'HI_INC_ENRL_2YR_TRANS_YR2_RT',
 'HI_INC_UNKN_ORIG_YR2_RT',
 'HI_INC_UNKN_4YR_TRANS_YR2_RT',
 'HI_INC_UNKN_2YR_TRANS_YR2_RT',
 'DEP_DEATH_YR2_RT',
 'DEP_COMP_ORIG_YR2_RT',
 'DEP_COMP_4YR_TRANS_YR2_RT',
 'DEP_COMP_2YR_TRANS_YR2_RT',
 'DEP_WDRAW_ORIG_YR2_RT',
 'DEP_WDRAW_4YR_TRANS_YR2_RT',
 'DEP_WDRAW_2YR_TRANS_YR2_RT',
 'DEP_ENRL_ORIG_YR2_RT',
 'DEP_ENRL_4YR_TRANS_YR2_RT',
 'DEP_ENRL_2YR_TRANS_YR2_RT',
 'DEP_UNKN_ORIG_YR2_RT',
 'DEP_UNKN_4YR_TRANS_YR2_RT',
 'DEP_UNKN_2YR_TRANS_YR2_RT',
 'IND_DEATH_YR2_RT',
 'IND_COMP_ORIG_YR2_RT',
 'IND_COMP_4YR_TRANS_YR2_RT',
 'IND_COMP_2YR_TRANS_YR2_RT',
 'IND_WDRAW_ORIG_YR2_RT',
 'IND_WDRAW_4YR_TRANS_YR2_RT',
 'IND_WDRAW_2YR_TRANS_YR2_RT',
 'IND_ENRL_ORIG_YR2_RT',
 'IND_ENRL_4YR_TRANS_YR2_RT',
 'IND_ENRL_2YR_TRANS_YR2_RT',
 'IND_UNKN_ORIG_YR2_RT',
 'IND_UNKN_4YR_TRANS_YR2_RT',
 'IND_UNKN_2YR_TRANS_YR2_RT',
 'FEMALE_DEATH_YR2_RT',
 'FEMALE_COMP_ORIG_YR2_RT',
 'FEMALE_COMP_4YR_TRANS_YR2_RT',
 'FEMALE_COMP_2YR_TRANS_YR2_RT',
 'FEMALE_WDRAW_ORIG_YR2_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR2_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR2_RT',
 'FEMALE_ENRL_ORIG_YR2_RT',
 'FEMALE_ENRL_4YR_TRANS_YR2_RT',
 'FEMALE_ENRL_2YR_TRANS_YR2_RT',
 'FEMALE_UNKN_ORIG_YR2_RT',
 'FEMALE_UNKN_4YR_TRANS_YR2_RT',
 'FEMALE_UNKN_2YR_TRANS_YR2_RT',
 'MALE_DEATH_YR2_RT',
 'MALE_COMP_ORIG_YR2_RT',
 'MALE_COMP_4YR_TRANS_YR2_RT',
 'MALE_COMP_2YR_TRANS_YR2_RT',
 'MALE_WDRAW_ORIG_YR2_RT',
 'MALE_WDRAW_4YR_TRANS_YR2_RT',
 'MALE_WDRAW_2YR_TRANS_YR2_RT',
 'MALE_ENRL_ORIG_YR2_RT',
 'MALE_ENRL_4YR_TRANS_YR2_RT',
 'MALE_ENRL_2YR_TRANS_YR2_RT',
 'MALE_UNKN_ORIG_YR2_RT',
 'MALE_UNKN_4YR_TRANS_YR2_RT',
 'MALE_UNKN_2YR_TRANS_YR2_RT',
 'PELL_DEATH_YR2_RT',
 'PELL_COMP_ORIG_YR2_RT',
 'PELL_COMP_4YR_TRANS_YR2_RT',
 'PELL_COMP_2YR_TRANS_YR2_RT',
 'PELL_WDRAW_ORIG_YR2_RT',
 'PELL_WDRAW_4YR_TRANS_YR2_RT',
 'PELL_WDRAW_2YR_TRANS_YR2_RT',
 'PELL_ENRL_ORIG_YR2_RT',
 'PELL_ENRL_4YR_TRANS_YR2_RT',
 'PELL_ENRL_2YR_TRANS_YR2_RT',
 'PELL_UNKN_ORIG_YR2_RT',
 'PELL_UNKN_4YR_TRANS_YR2_RT',
 'PELL_UNKN_2YR_TRANS_YR2_RT',
 'NOPELL_DEATH_YR2_RT',
 'NOPELL_COMP_ORIG_YR2_RT',
 'NOPELL_COMP_4YR_TRANS_YR2_RT',
 'NOPELL_COMP_2YR_TRANS_YR2_RT',
 'NOPELL_WDRAW_ORIG_YR2_RT',
 'NOPELL_WDRAW_4YR_TRANS_YR2_RT',
 'NOPELL_WDRAW_2YR_TRANS_YR2_RT',
 'NOPELL_ENRL_ORIG_YR2_RT',
 'NOPELL_ENRL_4YR_TRANS_YR2_RT',
 'NOPELL_ENRL_2YR_TRANS_YR2_RT',
 'NOPELL_UNKN_ORIG_YR2_RT',
 'NOPELL_UNKN_4YR_TRANS_YR2_RT',
 'NOPELL_UNKN_2YR_TRANS_YR2_RT',
 'LOAN_DEATH_YR2_RT',
 'LOAN_COMP_ORIG_YR2_RT',
 'LOAN_COMP_4YR_TRANS_YR2_RT',
 'LOAN_COMP_2YR_TRANS_YR2_RT',
 'LOAN_WDRAW_ORIG_YR2_RT',
 'LOAN_WDRAW_4YR_TRANS_YR2_RT',
 'LOAN_WDRAW_2YR_TRANS_YR2_RT',
 'LOAN_ENRL_ORIG_YR2_RT',
 'LOAN_ENRL_4YR_TRANS_YR2_RT',
 'LOAN_ENRL_2YR_TRANS_YR2_RT',
 'LOAN_UNKN_ORIG_YR2_RT',
 'LOAN_UNKN_4YR_TRANS_YR2_RT',
 'LOAN_UNKN_2YR_TRANS_YR2_RT',
 'NOLOAN_DEATH_YR2_RT',
 'NOLOAN_COMP_ORIG_YR2_RT',
 'NOLOAN_COMP_4YR_TRANS_YR2_RT',
 'NOLOAN_COMP_2YR_TRANS_YR2_RT',
 'NOLOAN_WDRAW_ORIG_YR2_RT',
 'NOLOAN_WDRAW_4YR_TRANS_YR2_RT',
 'NOLOAN_WDRAW_2YR_TRANS_YR2_RT',
 'NOLOAN_ENRL_ORIG_YR2_RT',
 'NOLOAN_ENRL_4YR_TRANS_YR2_RT',
 'NOLOAN_ENRL_2YR_TRANS_YR2_RT',
 'NOLOAN_UNKN_ORIG_YR2_RT',
 'NOLOAN_UNKN_4YR_TRANS_YR2_RT',
 'NOLOAN_UNKN_2YR_TRANS_YR2_RT',
 'FIRSTGEN_DEATH_YR2_RT',
 'FIRSTGEN_COMP_ORIG_YR2_RT',
 'FIRSTGEN_COMP_4YR_TRANS_YR2_RT',
 'FIRSTGEN_COMP_2YR_TRANS_YR2_RT',
 'FIRSTGEN_WDRAW_ORIG_YR2_RT',
 'FIRSTGEN_WDRAW_4YR_TRANS_YR2_RT',
 'FIRSTGEN_WDRAW_2YR_TRANS_YR2_RT',
 'FIRSTGEN_ENRL_ORIG_YR2_RT',
 'FIRSTGEN_ENRL_4YR_TRANS_YR2_RT',
 'FIRSTGEN_ENRL_2YR_TRANS_YR2_RT',
 'FIRSTGEN_UNKN_ORIG_YR2_RT',
 'FIRSTGEN_UNKN_4YR_TRANS_YR2_RT',
 'FIRSTGEN_UNKN_2YR_TRANS_YR2_RT',
 'NOT1STGEN_DEATH_YR2_RT',
 'NOT1STGEN_COMP_ORIG_YR2_RT',
 'NOT1STGEN_COMP_4YR_TRANS_YR2_RT',
 'NOT1STGEN_COMP_2YR_TRANS_YR2_RT',
 'NOT1STGEN_WDRAW_ORIG_YR2_RT',
 'NOT1STGEN_WDRAW_4YR_TRANS_YR2_RT',
 'NOT1STGEN_WDRAW_2YR_TRANS_YR2_RT',
 'NOT1STGEN_ENRL_ORIG_YR2_RT',
 'NOT1STGEN_ENRL_4YR_TRANS_YR2_RT',
 'NOT1STGEN_ENRL_2YR_TRANS_YR2_RT',
 'NOT1STGEN_UNKN_ORIG_YR2_RT',
 'NOT1STGEN_UNKN_4YR_TRANS_YR2_RT',
 'NOT1STGEN_UNKN_2YR_TRANS_YR2_RT',
 'DEATH_YR3_RT',
 'COMP_ORIG_YR3_RT',
 'COMP_4YR_TRANS_YR3_RT',
 'COMP_2YR_TRANS_YR3_RT',
 'WDRAW_ORIG_YR3_RT',
 'WDRAW_4YR_TRANS_YR3_RT',
 'WDRAW_2YR_TRANS_YR3_RT',
 'ENRL_ORIG_YR3_RT',
 'ENRL_4YR_TRANS_YR3_RT',
 'ENRL_2YR_TRANS_YR3_RT',
 'UNKN_ORIG_YR3_RT',
 'UNKN_4YR_TRANS_YR3_RT',
 'UNKN_2YR_TRANS_YR3_RT',
 'LO_INC_DEATH_YR3_RT',
 'LO_INC_COMP_ORIG_YR3_RT',
 'LO_INC_COMP_4YR_TRANS_YR3_RT',
 'LO_INC_COMP_2YR_TRANS_YR3_RT',
 'LO_INC_WDRAW_ORIG_YR3_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR3_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR3_RT',
 'LO_INC_ENRL_ORIG_YR3_RT',
 'LO_INC_ENRL_4YR_TRANS_YR3_RT',
 'LO_INC_ENRL_2YR_TRANS_YR3_RT',
 'LO_INC_UNKN_ORIG_YR3_RT',
 'LO_INC_UNKN_4YR_TRANS_YR3_RT',
 'LO_INC_UNKN_2YR_TRANS_YR3_RT',
 'MD_INC_DEATH_YR3_RT',
 'MD_INC_COMP_ORIG_YR3_RT',
 'MD_INC_COMP_4YR_TRANS_YR3_RT',
 'MD_INC_COMP_2YR_TRANS_YR3_RT',
 'MD_INC_WDRAW_ORIG_YR3_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR3_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR3_RT',
 'MD_INC_ENRL_ORIG_YR3_RT',
 'MD_INC_ENRL_4YR_TRANS_YR3_RT',
 'MD_INC_ENRL_2YR_TRANS_YR3_RT',
 'MD_INC_UNKN_ORIG_YR3_RT',
 'MD_INC_UNKN_4YR_TRANS_YR3_RT',
 'MD_INC_UNKN_2YR_TRANS_YR3_RT',
 'HI_INC_DEATH_YR3_RT',
 'HI_INC_COMP_ORIG_YR3_RT',
 'HI_INC_COMP_4YR_TRANS_YR3_RT',
 'HI_INC_COMP_2YR_TRANS_YR3_RT',
 'HI_INC_WDRAW_ORIG_YR3_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR3_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR3_RT',
 'HI_INC_ENRL_ORIG_YR3_RT',
 'HI_INC_ENRL_4YR_TRANS_YR3_RT',
 'HI_INC_ENRL_2YR_TRANS_YR3_RT',
 'HI_INC_UNKN_ORIG_YR3_RT',
 'HI_INC_UNKN_4YR_TRANS_YR3_RT',
 'HI_INC_UNKN_2YR_TRANS_YR3_RT',
 'DEP_DEATH_YR3_RT',
 'DEP_COMP_ORIG_YR3_RT',
 'DEP_COMP_4YR_TRANS_YR3_RT',
 'DEP_COMP_2YR_TRANS_YR3_RT',
 'DEP_WDRAW_ORIG_YR3_RT',
 'DEP_WDRAW_4YR_TRANS_YR3_RT',
 'DEP_WDRAW_2YR_TRANS_YR3_RT',
 'DEP_ENRL_ORIG_YR3_RT',
 'DEP_ENRL_4YR_TRANS_YR3_RT',
 'DEP_ENRL_2YR_TRANS_YR3_RT',
 'DEP_UNKN_ORIG_YR3_RT',
 'DEP_UNKN_4YR_TRANS_YR3_RT',
 'DEP_UNKN_2YR_TRANS_YR3_RT',
 'IND_DEATH_YR3_RT',
 'IND_COMP_ORIG_YR3_RT',
 'IND_COMP_4YR_TRANS_YR3_RT',
 'IND_COMP_2YR_TRANS_YR3_RT',
 'IND_WDRAW_ORIG_YR3_RT',
 'IND_WDRAW_4YR_TRANS_YR3_RT',
 'IND_WDRAW_2YR_TRANS_YR3_RT',
 'IND_ENRL_ORIG_YR3_RT',
 'IND_ENRL_4YR_TRANS_YR3_RT',
 'IND_ENRL_2YR_TRANS_YR3_RT',
 'IND_UNKN_ORIG_YR3_RT',
 'IND_UNKN_4YR_TRANS_YR3_RT',
 'IND_UNKN_2YR_TRANS_YR3_RT',
 'FEMALE_DEATH_YR3_RT',
 'FEMALE_COMP_ORIG_YR3_RT',
 'FEMALE_COMP_4YR_TRANS_YR3_RT',
 'FEMALE_COMP_2YR_TRANS_YR3_RT',
 'FEMALE_WDRAW_ORIG_YR3_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR3_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR3_RT',
 'FEMALE_ENRL_ORIG_YR3_RT',
 'FEMALE_ENRL_4YR_TRANS_YR3_RT',
 'FEMALE_ENRL_2YR_TRANS_YR3_RT',
 'FEMALE_UNKN_ORIG_YR3_RT',
 'FEMALE_UNKN_4YR_TRANS_YR3_RT',
 'FEMALE_UNKN_2YR_TRANS_YR3_RT',
 'MALE_DEATH_YR3_RT',
 'MALE_COMP_ORIG_YR3_RT',
 'MALE_COMP_4YR_TRANS_YR3_RT',
 'MALE_COMP_2YR_TRANS_YR3_RT',
 'MALE_WDRAW_ORIG_YR3_RT',
 'MALE_WDRAW_4YR_TRANS_YR3_RT',
 'MALE_WDRAW_2YR_TRANS_YR3_RT',
 'MALE_ENRL_ORIG_YR3_RT',
 'MALE_ENRL_4YR_TRANS_YR3_RT',
 'MALE_ENRL_2YR_TRANS_YR3_RT',
 'MALE_UNKN_ORIG_YR3_RT',
 'MALE_UNKN_4YR_TRANS_YR3_RT',
 'MALE_UNKN_2YR_TRANS_YR3_RT',
 'PELL_DEATH_YR3_RT',
 'PELL_COMP_ORIG_YR3_RT',
 'PELL_COMP_4YR_TRANS_YR3_RT',
 'PELL_COMP_2YR_TRANS_YR3_RT',
 'PELL_WDRAW_ORIG_YR3_RT',
 'PELL_WDRAW_4YR_TRANS_YR3_RT',
 'PELL_WDRAW_2YR_TRANS_YR3_RT',
 'PELL_ENRL_ORIG_YR3_RT',
 'PELL_ENRL_4YR_TRANS_YR3_RT',
 'PELL_ENRL_2YR_TRANS_YR3_RT',
 'PELL_UNKN_ORIG_YR3_RT',
 'PELL_UNKN_4YR_TRANS_YR3_RT',
 'PELL_UNKN_2YR_TRANS_YR3_RT',
 'NOPELL_DEATH_YR3_RT',
 'NOPELL_COMP_ORIG_YR3_RT',
 'NOPELL_COMP_4YR_TRANS_YR3_RT',
 'NOPELL_COMP_2YR_TRANS_YR3_RT',
 'NOPELL_WDRAW_ORIG_YR3_RT',
 'NOPELL_WDRAW_4YR_TRANS_YR3_RT',
 'NOPELL_WDRAW_2YR_TRANS_YR3_RT',
 'NOPELL_ENRL_ORIG_YR3_RT',
 'NOPELL_ENRL_4YR_TRANS_YR3_RT',
 'NOPELL_ENRL_2YR_TRANS_YR3_RT',
 'NOPELL_UNKN_ORIG_YR3_RT',
 'NOPELL_UNKN_4YR_TRANS_YR3_RT',
 'NOPELL_UNKN_2YR_TRANS_YR3_RT',
 'LOAN_DEATH_YR3_RT',
 'LOAN_COMP_ORIG_YR3_RT',
 'LOAN_COMP_4YR_TRANS_YR3_RT',
 'LOAN_COMP_2YR_TRANS_YR3_RT',
 'LOAN_WDRAW_ORIG_YR3_RT',
 'LOAN_WDRAW_4YR_TRANS_YR3_RT',
 'LOAN_WDRAW_2YR_TRANS_YR3_RT',
 'LOAN_ENRL_ORIG_YR3_RT',
 'LOAN_ENRL_4YR_TRANS_YR3_RT',
 'LOAN_ENRL_2YR_TRANS_YR3_RT',
 'LOAN_UNKN_ORIG_YR3_RT',
 'LOAN_UNKN_4YR_TRANS_YR3_RT',
 'LOAN_UNKN_2YR_TRANS_YR3_RT',
 'NOLOAN_DEATH_YR3_RT',
 'NOLOAN_COMP_ORIG_YR3_RT',
 'NOLOAN_COMP_4YR_TRANS_YR3_RT',
 'NOLOAN_COMP_2YR_TRANS_YR3_RT',
 'NOLOAN_WDRAW_ORIG_YR3_RT',
 'NOLOAN_WDRAW_4YR_TRANS_YR3_RT',
 'NOLOAN_WDRAW_2YR_TRANS_YR3_RT',
 'NOLOAN_ENRL_ORIG_YR3_RT',
 'NOLOAN_ENRL_4YR_TRANS_YR3_RT',
 'NOLOAN_ENRL_2YR_TRANS_YR3_RT',
 'NOLOAN_UNKN_ORIG_YR3_RT',
 'NOLOAN_UNKN_4YR_TRANS_YR3_RT',
 'NOLOAN_UNKN_2YR_TRANS_YR3_RT',
 'FIRSTGEN_DEATH_YR3_RT',
 'FIRSTGEN_COMP_ORIG_YR3_RT',
 'FIRSTGEN_COMP_4YR_TRANS_YR3_RT',
 'FIRSTGEN_COMP_2YR_TRANS_YR3_RT',
 'FIRSTGEN_WDRAW_ORIG_YR3_RT',
 'FIRSTGEN_WDRAW_4YR_TRANS_YR3_RT',
 'FIRSTGEN_WDRAW_2YR_TRANS_YR3_RT',
 'FIRSTGEN_ENRL_ORIG_YR3_RT',
 'FIRSTGEN_ENRL_4YR_TRANS_YR3_RT',
 'FIRSTGEN_ENRL_2YR_TRANS_YR3_RT',
 'FIRSTGEN_UNKN_ORIG_YR3_RT',
 'FIRSTGEN_UNKN_4YR_TRANS_YR3_RT',
 'FIRSTGEN_UNKN_2YR_TRANS_YR3_RT',
 'NOT1STGEN_DEATH_YR3_RT',
 'NOT1STGEN_COMP_ORIG_YR3_RT',
 'NOT1STGEN_COMP_4YR_TRANS_YR3_RT',
 'NOT1STGEN_COMP_2YR_TRANS_YR3_RT',
 'NOT1STGEN_WDRAW_ORIG_YR3_RT',
 'NOT1STGEN_WDRAW_4YR_TRANS_YR3_RT',
 'NOT1STGEN_WDRAW_2YR_TRANS_YR3_RT',
 'NOT1STGEN_ENRL_ORIG_YR3_RT',
 'NOT1STGEN_ENRL_4YR_TRANS_YR3_RT',
 'NOT1STGEN_ENRL_2YR_TRANS_YR3_RT',
 'NOT1STGEN_UNKN_ORIG_YR3_RT',
 'NOT1STGEN_UNKN_4YR_TRANS_YR3_RT',
 'NOT1STGEN_UNKN_2YR_TRANS_YR3_RT',
 'DEATH_YR4_RT',
 'COMP_ORIG_YR4_RT',
 'COMP_4YR_TRANS_YR4_RT',
 'COMP_2YR_TRANS_YR4_RT',
 'WDRAW_ORIG_YR4_RT',
 'WDRAW_4YR_TRANS_YR4_RT',
 'WDRAW_2YR_TRANS_YR4_RT',
 'ENRL_ORIG_YR4_RT',
 'ENRL_4YR_TRANS_YR4_RT',
 'ENRL_2YR_TRANS_YR4_RT',
 'UNKN_ORIG_YR4_RT',
 'UNKN_4YR_TRANS_YR4_RT',
 'UNKN_2YR_TRANS_YR4_RT',
 'LO_INC_DEATH_YR4_RT',
 'LO_INC_COMP_ORIG_YR4_RT',
 'LO_INC_COMP_4YR_TRANS_YR4_RT',
 'LO_INC_COMP_2YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_ORIG_YR4_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR4_RT',
 'LO_INC_ENRL_ORIG_YR4_RT',
 'LO_INC_ENRL_4YR_TRANS_YR4_RT',
 'LO_INC_ENRL_2YR_TRANS_YR4_RT',
 'LO_INC_UNKN_ORIG_YR4_RT',
 'LO_INC_UNKN_4YR_TRANS_YR4_RT',
 'LO_INC_UNKN_2YR_TRANS_YR4_RT',
 'MD_INC_DEATH_YR4_RT',
 'MD_INC_COMP_ORIG_YR4_RT',
 'MD_INC_COMP_4YR_TRANS_YR4_RT',
 'MD_INC_COMP_2YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_ORIG_YR4_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR4_RT',
 'MD_INC_ENRL_ORIG_YR4_RT',
 'MD_INC_ENRL_4YR_TRANS_YR4_RT',
 'MD_INC_ENRL_2YR_TRANS_YR4_RT',
 'MD_INC_UNKN_ORIG_YR4_RT',
 'MD_INC_UNKN_4YR_TRANS_YR4_RT',
 'MD_INC_UNKN_2YR_TRANS_YR4_RT',
 'HI_INC_DEATH_YR4_RT',
 'HI_INC_COMP_ORIG_YR4_RT',
 'HI_INC_COMP_4YR_TRANS_YR4_RT',
 'HI_INC_COMP_2YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_ORIG_YR4_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR4_RT',
 'HI_INC_ENRL_ORIG_YR4_RT',
 'HI_INC_ENRL_4YR_TRANS_YR4_RT',
 'HI_INC_ENRL_2YR_TRANS_YR4_RT',
 'HI_INC_UNKN_ORIG_YR4_RT',
 'HI_INC_UNKN_4YR_TRANS_YR4_RT',
 'HI_INC_UNKN_2YR_TRANS_YR4_RT',
 'DEP_DEATH_YR4_RT',
 'DEP_COMP_ORIG_YR4_RT',
 'DEP_COMP_4YR_TRANS_YR4_RT',
 'DEP_COMP_2YR_TRANS_YR4_RT',
 'DEP_WDRAW_ORIG_YR4_RT',
 'DEP_WDRAW_4YR_TRANS_YR4_RT',
 'DEP_WDRAW_2YR_TRANS_YR4_RT',
 'DEP_ENRL_ORIG_YR4_RT',
 'DEP_ENRL_4YR_TRANS_YR4_RT',
 'DEP_ENRL_2YR_TRANS_YR4_RT',
 'DEP_UNKN_ORIG_YR4_RT',
 'DEP_UNKN_4YR_TRANS_YR4_RT',
 'DEP_UNKN_2YR_TRANS_YR4_RT',
 'IND_DEATH_YR4_RT',
 'IND_COMP_ORIG_YR4_RT',
 'IND_COMP_4YR_TRANS_YR4_RT',
 'IND_COMP_2YR_TRANS_YR4_RT',
 'IND_WDRAW_ORIG_YR4_RT',
 'IND_WDRAW_4YR_TRANS_YR4_RT',
 'IND_WDRAW_2YR_TRANS_YR4_RT',
 'IND_ENRL_ORIG_YR4_RT',
 'IND_ENRL_4YR_TRANS_YR4_RT',
 'IND_ENRL_2YR_TRANS_YR4_RT',
 'IND_UNKN_ORIG_YR4_RT',
 'IND_UNKN_4YR_TRANS_YR4_RT',
 'IND_UNKN_2YR_TRANS_YR4_RT',
 'FEMALE_DEATH_YR4_RT',
 'FEMALE_COMP_ORIG_YR4_RT',
 'FEMALE_COMP_4YR_TRANS_YR4_RT',
 'FEMALE_COMP_2YR_TRANS_YR4_RT',
 'FEMALE_WDRAW_ORIG_YR4_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR4_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR4_RT',
 'FEMALE_ENRL_ORIG_YR4_RT',
 'FEMALE_ENRL_4YR_TRANS_YR4_RT',
 'FEMALE_ENRL_2YR_TRANS_YR4_RT',
 'FEMALE_UNKN_ORIG_YR4_RT',
 'FEMALE_UNKN_4YR_TRANS_YR4_RT',
 'FEMALE_UNKN_2YR_TRANS_YR4_RT',
 'MALE_DEATH_YR4_RT',
 'MALE_COMP_ORIG_YR4_RT',
 'MALE_COMP_4YR_TRANS_YR4_RT',
 'MALE_COMP_2YR_TRANS_YR4_RT',

In [5]:
scorecard_fos.shape

(229188, 174)

In [6]:
scorecard_fos.columns.tolist()

['UNITID',
 'OPEID6',
 'INSTNM',
 'CONTROL',
 'MAIN',
 'CIPCODE',
 'CIPDESC',
 'CREDLEV',
 'CREDDESC',
 'IPEDSCOUNT1',
 'IPEDSCOUNT2',
 'DEBT_ALL_STGP_ANY_N',
 'DEBT_ALL_STGP_ANY_MEAN',
 'DEBT_ALL_STGP_ANY_MDN',
 'DEBT_ALL_STGP_EVAL_N',
 'DEBT_ALL_STGP_EVAL_MEAN',
 'DEBT_ALL_STGP_EVAL_MDN',
 'DEBT_ALL_PP_ANY_N',
 'DEBT_ALL_PP_ANY_MEAN',
 'DEBT_ALL_PP_ANY_MDN',
 'DEBT_ALL_PP_EVAL_N',
 'DEBT_ALL_PP_EVAL_MEAN',
 'DEBT_ALL_PP_EVAL_MDN',
 'DEBT_MALE_STGP_ANY_N',
 'DEBT_MALE_STGP_ANY_MEAN',
 'DEBT_MALE_STGP_ANY_MDN',
 'DEBT_MALE_STGP_EVAL_N',
 'DEBT_MALE_STGP_EVAL_MEAN',
 'DEBT_MALE_STGP_EVAL_MDN',
 'DEBT_MALE_PP_ANY_N',
 'DEBT_MALE_PP_ANY_MEAN',
 'DEBT_MALE_PP_ANY_MDN',
 'DEBT_MALE_PP_EVAL_N',
 'DEBT_MALE_PP_EVAL_MEAN',
 'DEBT_MALE_PP_EVAL_MDN',
 'DEBT_NOTMALE_STGP_ANY_N',
 'DEBT_NOTMALE_STGP_ANY_MEAN',
 'DEBT_NOTMALE_STGP_ANY_MDN',
 'DEBT_NOTMALE_STGP_EVAL_N',
 'DEBT_NOTMALE_STGP_EVAL_MEAN',
 'DEBT_NOTMALE_STGP_EVAL_MDN',
 'DEBT_NOTMALE_PP_ANY_N',
 'DEBT_NOTMALE_PP_ANY_MEAN',
 'DEBT_NOTMALE_PP_ANY_MDN',
 'DEBT_NOTMALE_PP_EVAL_N',
 'DEBT_NOTMALE_PP_EVAL_MEAN',
 'DEBT_NOTMALE_PP_EVAL_MDN',
 'DEBT_PELL_STGP_ANY_N',
 'DEBT_PELL_STGP_ANY_MEAN',
 'DEBT_PELL_STGP_ANY_MDN',
 'DEBT_PELL_STGP_EVAL_N',
 'DEBT_PELL_STGP_EVAL_MEAN',
 'DEBT_PELL_STGP_EVAL_MDN',
 'DEBT_PELL_PP_ANY_N',
 'DEBT_PELL_PP_ANY_MEAN',
 'DEBT_PELL_PP_ANY_MDN',
 'DEBT_PELL_PP_EVAL_N',
 'DEBT_PELL_PP_EVAL_MEAN',
 'DEBT_PELL_PP_EVAL_MDN',
 'DEBT_NOPELL_STGP_ANY_N',
 'DEBT_NOPELL_STGP_ANY_MEAN',
 'DEBT_NOPELL_STGP_ANY_MDN',
 'DEBT_NOPELL_STGP_EVAL_N',
 'DEBT_NOPELL_STGP_EVAL_MEAN',
 'DEBT_NOPELL_STGP_EVAL_MDN',
 'DEBT_NOPELL_PP_ANY_N',
 'DEBT_NOPELL_PP_ANY_MEAN',
 'DEBT_NOPELL_PP_ANY_MDN',
 'DEBT_NOPELL_PP_EVAL_N',
 'DEBT_NOPELL_PP_EVAL_MEAN',
 'DEBT_NOPELL_PP_EVAL_MDN',
 'DEBT_ALL_PP_ANY_MDN10YRPAY',
 'DEBT_ALL_PP_EVAL_MDN10YRPAY',
 'DEBT_ALL_STGP_ANY_MDN10YRPAY',
 'DEBT_ALL_STGP_EVAL_MDN10YRPAY',
 'EARN_COUNT_NWNE_HI_1YR',
 'EARN_CNTOVER150_HI_1YR',
 'EARN_COUNT_WNE_HI_1YR',
 'EARN_MDN_HI_1YR',
 'EARN_COUNT_NWNE_HI_2YR',
 'EARN_CNTOVER150_HI_2YR',
 'EARN_COUNT_WNE_HI_2YR',
 'EARN_MDN_HI_2YR',
 'BBRR2_FED_COMP_N',
 'BBRR2_FED_COMP_DFLT',
 'BBRR2_FED_COMP_DLNQ',
 'BBRR2_FED_COMP_FBR',
 'BBRR2_FED_COMP_DFR',
 'BBRR2_FED_COMP_NOPROG',
 'BBRR2_FED_COMP_MAKEPROG',
 'BBRR2_FED_COMP_PAIDINFULL',
 'BBRR2_FED_COMP_DISCHARGE',
 'BBRR3_FED_COMP_N',
 'BBRR3_FED_COMP_DFLT',
 'BBRR3_FED_COMP_DLNQ',
 'BBRR3_FED_COMP_FBR',
 'BBRR3_FED_COMP_DFR',
 'BBRR3_FED_COMP_NOPROG',
 'BBRR3_FED_COMP_MAKEPROG',
 'BBRR3_FED_COMP_PAIDINFULL',
 'BBRR3_FED_COMP_DISCHARGE',
 'EARN_COUNT_PELL_WNE_1YR',
 'EARN_PELL_WNE_MDN_1YR',
 'EARN_COUNT_NOPELL_WNE_1YR',
 'EARN_NOPELL_WNE_MDN_1YR',
 'EARN_COUNT_MALE_WNE_1YR',
 'EARN_MALE_WNE_MDN_1YR',
 'EARN_COUNT_NOMALE_WNE_1YR',
 'EARN_NOMALE_WNE_MDN_1YR',
 'EARN_COUNT_NE_3YR',
 'EARN_NE_MDN_3YR',
 'EARN_COUNT_WNE_3YR',
 'EARN_CNTOVER150_3YR',
 'EARN_COUNT_PELL_NE_3YR',
 'EARN_PELL_NE_MDN_3YR',
 'EARN_COUNT_NOPELL_NE_3YR',
 'EARN_NOPELL_NE_MDN_3YR',
 'EARN_COUNT_MALE_NE_3YR',
 'EARN_MALE_NE_MDN_3YR',
 'EARN_COUNT_NOMALE_NE_3YR',
 'EARN_NOMALE_NE_MDN_3YR',
 'EARN_COUNT_NWNE_1YR',
 'EARN_COUNT_WNE_1YR',
 'EARN_MDN_1YR',
 'EARN_GT_THRESHOLD_1YR',
 'EARN_COUNT_HIGH_CRED_1YR',
 'EARN_IN_STATE_1YR',
 'EARN_COUNT_NWNE_4YR',
 'EARN_COUNT_WNE_4YR',
 'EARN_MDN_4YR',
 'EARN_GT_THRESHOLD_4YR',
 'EARN_COUNT_PELL_WNE_4YR',
 'EARN_PELL_WNE_MDN_4YR',
 'EARN_COUNT_NOPELL_WNE_4YR',
 'EARN_NOPELL_WNE_MDN_4YR',
 'EARN_COUNT_MALE_WNE_4YR',
 'EARN_MALE_WNE_MDN_4YR',
 'EARN_COUNT_NOMALE_WNE_4YR',
 'EARN_NOMALE_WNE_MDN_4YR',
 'EARN_COUNT_HIGH_CRED_4YR',
 'EARN_IN_STATE_4YR',
 'BBRR1_FED_COMP_N',
 'BBRR1_FED_COMP_DFLT',
 'BBRR1_FED_COMP_DLNQ',
 'BBRR1_FED_COMP_FBR',
 'BBRR1_FED_COMP_DFR',
 'BBRR1_FED_COMP_NOPROG',
 'BBRR1_FED_COMP_MAKEPROG',
 'BBRR1_FED_COMP_PAIDINFULL',
 'BBRR1_FED_COMP_DISCHARGE',
 'BBRR4_FED_COMP_N',
 'BBRR4_FED_COMP_DFLT',
 'BBRR4_FED_COMP_DLNQ',
 'BBRR4_FED_COMP_FBR',
 'BBRR4_FED_COMP_DFR',
 'BBRR4_FED_COMP_NOPROG',
 'BBRR4_FED_COMP_MAKEPROG',
 'BBRR4_FED_COMP_PAIDINFULL',
 'BBRR4_FED_COMP_DISCHARGE',
 'DISTANCE',
 'EARN_COUNT_NWNE_5YR',
 'EARN_COUNT_WNE_5YR',
 'EARN_MDN_5YR',
 'EARN_GT_THRESHOLD_5YR',
 'EARN_COUNT_PELL_WNE_5YR',
 'EARN_PELL_WNE_MDN_5YR',
 'EARN_COUNT_NOPELL_WNE_5YR',
 'EARN_NOPELL_WNE_MDN_5YR',
 'EARN_COUNT_MALE_WNE_5YR',
 'EARN_MALE_WNE_MDN_5YR',
 'EARN_COUNT_NOMALE_WNE_5YR',
 'EARN_NOMALE_WNE_MDN_5YR',
 'EARN_COUNT_HIGH_CRED_5YR',
 'EARN_IN_STATE_5YR']

In [7]:
# Find earnings columns that may be useful later
[col for col in scorecard_fos.columns if "MDN_3YR".lower() in col.lower()]

['EARN_NE_MDN_3YR',
 'EARN_PELL_NE_MDN_3YR',
 'EARN_NOPELL_NE_MDN_3YR',
 'EARN_MALE_NE_MDN_3YR',
 'EARN_NOMALE_NE_MDN_3YR']

In [8]:
# Select columns from scorecard to keep. EARN_NE_MDN_3YR provides median earnings 3 years after completion for non-enrolled students.
scorecard_fos_clean = scorecard_fos[[
    "UNITID"
    ,"INSTNM"
    ,"CIPCODE"
    ,"CIPDESC"
    ,"CREDLEV"
    ,"CREDDESC"
    ,"EARN_MDN_1YR"
    ,"EARN_NE_MDN_3YR"
    ,"EARN_MDN_5YR"
]].copy()

In [9]:
scorecard_fos_clean.rename(columns={
    "UNITID" : "unitid"
    ,"INSTNM" : "inst_name"
    ,"CIPCODE" : "cipcode"
    ,"CIPDESC" : "cip_desc"
    ,"CREDLEV" : "credlev"
    ,"CREDDESC" : "cred_desc"
    ,"EARN_MDN_1YR" : "median_earnings_1yr"
    ,"EARN_NE_MDN_3YR" : "median_earnings_3yr"
    ,"EARN_MDN_5YR" : "median_earnings_5yr"
}, inplace = True)

In [10]:
# Fix cip code to uniform xxxx dtype str format.
# Fill three digit codes to 4 digit with leading 0
scorecard_fos_clean["cip4"]= (
    scorecard_fos_clean["cipcode"]
    .astype(str)
    .str.zfill(4)
)

In [11]:
#Explore scorecard_il
scorecard_il.shape

(6429, 3306)

In [12]:
# Select columns from scorecard to keep.
scorecard_il_clean = scorecard_il[[
    "UNITID"
    ,"STABBR"
    ,"CONTROL"
    ,"COSTT4_A"
    ,"COSTT4_P"
    ,"NPT4_PUB"
    ,"NPT4_PRIV"
]].copy()

In [13]:
# Clean columns for naming conventions
scorecard_il_clean.rename(columns={
    "UNITID" : "unitid"
    ,"STABBR" : "state"
    ,"CONTROL" : "control"
    ,"COSTT4_A" : "avg_annual_tuition_housing"
    ,"COSTT4_P" : "avg_annual_tuition"
    ,"NPT4_PUB" : "avg_net_price_pub"
    ,"NPT4_PRIV" : "avg_net_price_priv"
}, inplace = True)

In [14]:
scorecard_il_clean.columns

Index(['unitid', 'state', 'control', 'avg_annual_tuition_housing',
       'avg_annual_tuition', 'avg_net_price_pub', 'avg_net_price_priv'],
      dtype='object')

In [15]:
# Get unitids for Tennessee institutions
tn_unitids = scorecard_il_clean[scorecard_il_clean["state"] == "TN"]["unitid"]

# Filter the field of study dataframe to only include Tennessee institutions
scorecard_fos_tn = scorecard_fos_clean[scorecard_fos_clean["unitid"].isin(tn_unitids)]

# Filter the institution-level dataframe to only include Tennessee institutions
scorecard_il_tn = scorecard_il_clean[scorecard_il_clean["state"] == "TN"]

In [16]:
scorecard_fos_tn.info

<bound method DataFrame.info of           unitid                                 inst_name  cipcode  \
162267  219505.0                  American Baptist College     2401
162268  219505.0                  American Baptist College     2401
162269  219505.0                  American Baptist College     2401
162270  219505.0                  American Baptist College     3802
162271  219505.0                  American Baptist College     3906
...          ...                                       ...      ...
219044  497125.0  Galen Health Institutes-Nashville Campus     5138
219048  497198.0          Academy of Allied Health Careers     5107
219049  497198.0          Academy of Allied Health Careers     5108
219050  497198.0          Academy of Allied Health Careers     5110
219051  497198.0          Academy of Allied Health Careers     5139

                                                 cip_desc  credlev  \
162267  Liberal Arts and Sciences, General Studies and...        2
162268  Liberal Arts and Sciences, General Studies and...        3
162269  Liberal Arts and Sciences, General Studies and...        4
162270                        Religion/Religious Studies.        1
162271               Theological and Ministerial Studies.        1
...                                                   ...      ...
219044  Registered Nursing, Nursing Administration, Nu...        3
219048        Health and Medical Administrative Services.        1
219049      Allied Health and Medical Assisting Services.        1
219050  Clinical/Medical Laboratory Science/Research a...        1
219051  Practical Nursing, Vocational Nursing and Nurs...        1

                                   cred_desc median_earnings_1yr  \
162267                    Associate's Degree                  PS
162268                     Bachelor's Degree                  PS
162269        Post-baccalaureate Certificate                  PS
162270  Undergraduate Certificate or Diploma                  PS
162271  Undergraduate Certificate or Diploma                  PS
...                                      ...                 ...
219044                     Bachelor's Degree               76234
219048  Undergraduate Certificate or Diploma                  PS
219049  Undergraduate Certificate or Diploma                  PS
219050  Undergraduate Certificate or Diploma                  PS
219051  Undergraduate Certificate or Diploma                  PS

       median_earnings_3yr median_earnings_5yr  cip4
162267                  PS                  PS  2401
162268                  PS                  PS  2401
162269                  PS                  PS  2401
162270                  PS                  PS  3802
162271                  PS                  PS  3906
...                    ...                 ...   ...
219044               72065               89101  5138
219048                 NaN                  PS  5107
219049                 NaN                  PS  5108
219050                 NaN                  PS  5110
219051                 NaN                  PS  5139

[4166 rows x 10 columns]>

In [17]:
scorecard_il_tn.info

<bound method DataFrame.info of         unitid state  control  avg_annual_tuition_housing  avg_annual_tuition  \
2961    219505    TN        2                     27241.0                 NaN
2962    219587    TN        3                         NaN             19400.0
2963    219596    TN        1                         NaN             10362.0
2964    219602    TN        1                     26790.0                 NaN
2965    219639    TN        2                     21438.0                 NaN
...        ...   ...      ...                         ...                 ...
6300  44376603    TN        3                         NaN                 NaN
6346  45519610    TN        3                         NaN                 NaN
6350  45519614    TN        3                         NaN                 NaN
6373  47503304    TN        2                         NaN                 NaN
6379  47503310    TN        2                         NaN                 NaN

      avg_net_price_pub  avg_net_price_priv
2961                NaN             19294.0
2962                NaN             10343.0
2963             3720.0                 NaN
2964            14846.0                 NaN
2965                NaN             13401.0
...                 ...                 ...
6300                NaN                 NaN
6346                NaN                 NaN
6350                NaN                 NaN
6373                NaN                 NaN
6379                NaN                 NaN

[153 rows x 7 columns]>

In [18]:
# Is NSS in the data set?
scorecard_fos_tn[scorecard_fos_tn["inst_name"].str.contains("Nashville Software", case=False, na=False)]

Empty DataFrame
Columns: [unitid, inst_name, cipcode, cip_desc, credlev, cred_desc, median_earnings_1yr, median_earnings_3yr, median_earnings_5yr, cip4]
Index: []

In [19]:
scorecard_fos_tn["cipcode"].value_counts()

cipcode
5202    134
5138    113
2401     85
5109     73
1312     68
       ...
405       1
406       1
105       1
1106      1
5126      1
Name: count, Length: 292, dtype: int64

In [20]:
scorecard_fos_tn["cipcode"].unique()

array([2401, 3802, 3906, 3999, 4400, 5009, 5207, 1204, 1504, 4603, 4701,
       4703, 4706, 4805, 5108, 5139, 5204,  100,  901,  904, 1101, 1105,
       1107, 1108, 1301, 1303, 1304, 1306, 1310, 1311, 1312, 1313, 1314,
       1412, 1500, 1506, 1601, 1612, 2301, 2601, 2611, 2701, 3105, 3801,
       4005, 4006, 4008, 4201, 4228, 4301, 4407, 4510, 4511, 4901, 5005,
       5007, 5107, 5109, 5110, 5111, 5115, 5138, 5201, 5202, 5203, 5208,
       5214, 5401, 5122,  301,  402,  408,  501,  909,  910, 1002, 1399,
       1605, 1609, 1611, 2200, 2201, 2602, 2615, 2703, 3099, 3800, 3902,
       3905, 4506, 4509, 5004, 5006, 5010, 5120, 5123, 5206, 5211, 5212,
       5213, 5219, 2613, 3005, 4299, 4303, 5100, 1401, 2313, 3001, 3008,
       3010, 3071, 3904, 5299, 1499, 1901, 1902, 1904, 1905, 1906, 1907,
       1909, 2699, 3101, 3899, 4402, 4599, 5131, 5132,  106,  183, 1503,
       1507, 1508, 1513, 2203, 3000, 3201, 4103, 4302, 4702, 4902, 5106,
       5135, 5199, 5209,  502, 1110, 1407, 1408, 1409, 1410, 1419, 1443,
       1515, 3018, 3033, 3070, 4304, 4507, 5205, 5220, 3907, 1109, 1502,
       1505, 1517, 4499, 4604, 5127, 3103, 4404, 4501, 5001,  302, 1199,
       1305, 2314, 3011, 3903, 4503, 4512, 5210, 1104, 1003, 1511, 2605,
       4502, 5102, 5112, 4605, 2604, 3023, 4227, 4699, 1203, 1302,  907,
       3046, 3601,  110, 1315,  999, 2305, 3020, 3199, 4504,  109,  180,
        181,  306, 5116, 3017, 1616, 2610, 5104, 4601,  403,  404,  409,
       1205, 1405, 2501, 3014, 3025, 4405,  101,  103,  111, 1442, 1510,
       5003, 5217, 1501, 1512, 5218, 4199, 5118, 1102, 2612, 4799,  305,
       1604, 3013, 5105, 1001, 1099, 5117, 1427, 3012, 3030,  108,  112,
        199,  405,  406, 1309, 1402, 1403, 1413, 1414, 1418, 1423, 1432,
       1435, 1699, 1999, 2202, 2399, 2705, 2799, 3006, 3019, 4399, 5099,
       1404, 5133, 3015, 2603, 2607, 3026, 1307, 2608, 2609, 3022, 4002,
       4010, 5114,  105, 1103, 1106, 5126])

In [21]:
scorecard_fos_tn.dtypes

unitid                 float64
inst_name               object
cipcode                  int64
cip_desc                object
credlev                  int64
cred_desc               object
median_earnings_1yr     object
median_earnings_3yr     object
median_earnings_5yr     object
cip4                    object
dtype: object

In [22]:
scorecard_il_tn.dtypes

unitid                          int64
state                          object
control                         int64
avg_annual_tuition_housing    float64
avg_annual_tuition            float64
avg_net_price_pub             float64
avg_net_price_priv            float64
dtype: object

In [23]:
# Join scorecard data sets
scorecard_tn = scorecard_fos_tn.merge(
    scorecard_il_tn,
    on='unitid',
    how='left'
)

scorecard = scorecard_fos.merge(
    scorecard_il,
    on='UNITID',
    how='left',   # or 'inner'
    validate='many_to_one'
)

In [24]:
scorecard_tn[['credlev', 'cred_desc']].drop_duplicates().sort_values('credlev')

     credlev                             cred_desc
3          1  Undergraduate Certificate or Diploma
0          2                    Associate's Degree
1          3                     Bachelor's Degree
2          4        Post-baccalaureate Certificate
8          5                       Master's Degree
35         6                       Doctoral Degree
110        7             First Professional Degree
30         8     Graduate/Professional Certificate

In [25]:
scorecard_tn[['median_earnings_1yr',
               'median_earnings_3yr',
               'median_earnings_5yr']].describe()

       median_earnings_1yr median_earnings_3yr median_earnings_5yr
count                 4166                3681                4166
unique                1083                 878                1022
top                     PS                  PS                  PS
freq                  3067                2787                3125

In [26]:
scorecard_tn.groupby('credlev')[
    ['median_earnings_1yr',
     'median_earnings_3yr',
     'median_earnings_5yr']
].apply(lambda x: x.isnull().mean())

         median_earnings_1yr  median_earnings_3yr  median_earnings_5yr
credlev
1                        0.0             0.165254                  0.0
2                        0.0             0.157692                  0.0
3                        0.0             0.072997                  0.0
4                        0.0             0.533333                  0.0
5                        0.0             0.118384                  0.0
6                        0.0             0.076577                  0.0
7                        0.0             0.193548                  0.0
8                        0.0             0.173729                  0.0

In [27]:
scorecard_tn['cred_desc'].value_counts()

cred_desc
Bachelor's Degree                       1685
Master's Degree                          718
Undergraduate Certificate or Diploma     708
Associate's Degree                       520
Graduate/Professional Certificate        236
Doctoral Degree                          222
First Professional Degree                 62
Post-baccalaureate Certificate            15
Name: count, dtype: int64

In [28]:
scorecard_tn.groupby(['cip4', 'cred_desc']).size().sort_values(ascending=False)

cip4  cred_desc
1204  Undergraduate Certificate or Diploma    47
5202  Bachelor's Degree                       38
2601  Bachelor's Degree                       37
5401  Bachelor's Degree                       36
2301  Bachelor's Degree                       36
                                              ..
0111  Master's Degree                          1
0112  Bachelor's Degree                        1
      Master's Degree                          1
0180  Doctoral Degree                          1
0181  Master's Degree                          1
Length: 855, dtype: int64

In [29]:
scorecard_tn['cred_desc'].value_counts()

cred_desc
Bachelor's Degree                       1685
Master's Degree                          718
Undergraduate Certificate or Diploma     708
Associate's Degree                       520
Graduate/Professional Certificate        236
Doctoral Degree                          222
First Professional Degree                 62
Post-baccalaureate Certificate            15
Name: count, dtype: int64

In [30]:
scorecard_tn.head()

,unitid,inst_name,cipcode,cip_desc,credlev,cred_desc,median_earnings_1yr,median_earnings_3yr,median_earnings_5yr,cip4,state,control,avg_annual_tuition_housing,avg_annual_tuition,avg_net_price_pub,avg_net_price_priv
0,219505.0,American Baptist College,2401,"Liberal Arts and Sciences, General Studies and...",2,Associate's Degree,PS,PS,PS,2401,TN,2,27241.0,NaN,NaN,19294.0
1,219505.0,American Baptist College,2401,"Liberal Arts and Sciences, General Studies and...",3,Bachelor's Degree,PS,PS,PS,2401,TN,2,27241.0,NaN,NaN,19294.0
2,219505.0,American Baptist College,2401,"Liberal Arts and Sciences, General Studies and...",4,Post-baccalaureate Certificate,PS,PS,PS,2401,TN,2,27241.0,NaN,NaN,19294.0
3,219505.0,American Baptist College,3802,Religion/Religious Studies.,1,Undergraduate Certificate or Diploma,PS,PS,PS,3802,TN,2,27241.0,NaN,NaN,19294.0
4,219505.0,American Baptist College,3906,Theological and Ministerial Studies.,1,Undergraduate Certificate or Diploma,PS,PS,PS,3906,TN,2,27241.0,NaN,NaN,19294.0

In [31]:
scorecard_tn.tail()

,unitid,inst_name,cipcode,cip_desc,credlev,cred_desc,median_earnings_1yr,median_earnings_3yr,median_earnings_5yr,cip4,state,control,avg_annual_tuition_housing,avg_annual_tuition,avg_net_price_pub,avg_net_price_priv
4161,497125.0,Galen Health Institutes-Nashville Campus,5138,"Registered Nursing, Nursing Administration, Nu...",3,Bachelor's Degree,76234,72065,89101,5138,TN,3,31743.0,NaN,NaN,27306.0
4162,497198.0,Academy of Allied Health Careers,5107,Health and Medical Administrative Services.,1,Undergraduate Certificate or Diploma,PS,NaN,PS,5107,TN,3,NaN,14372.0,NaN,9095.0
4163,497198.0,Academy of Allied Health Careers,5108,Allied Health and Medical Assisting Services.,1,Undergraduate Certificate or Diploma,PS,NaN,PS,5108,TN,3,NaN,14372.0,NaN,9095.0
4164,497198.0,Academy of Allied Health Careers,5110,Clinical/Medical Laboratory Science/Research a...,1,Undergraduate Certificate or Diploma,PS,NaN,PS,5110,TN,3,NaN,14372.0,NaN,9095.0
4165,497198.0,Academy of Allied Health Careers,5139,"Practical Nursing, Vocational Nursing and Nurs...",1,Undergraduate Certificate or Diploma,PS,NaN,PS,5139,TN,3,NaN,14372.0,NaN,9095.0

In [32]:
# Insepect earnings for viability
earn_1yr = scorecard_tn['median_earnings_1yr'].value_counts().to_frame()
earn_1yr

                     count
median_earnings_1yr
PS                    3067
26952                    3
84311                    2
52528                    2
52331                    2
...                    ...
22826                    1
24411                    1
31401                    1
26624                    1
65084                    1

[1083 rows x 1 columns]

In [33]:
earn_3yr = scorecard_tn['median_earnings_3yr'].value_counts().to_frame()
earn_3yr

                     count
median_earnings_3yr
PS                    2787
39833                    2
36609                    2
33693                    2
51761                    2
...                    ...
25930                    1
36908                    1
39004                    1
62412                    1
52342                    1

[878 rows x 1 columns]

In [34]:
earn_5yr = scorecard_tn['median_earnings_5yr'].value_counts().to_frame()
earn_5yr

                     count
median_earnings_5yr
PS                    3125
47664                    2
44034                    2
40094                    2
28474                    2
...                    ...
28737                    1
50175                    1
43920                    1
78480                    1
43477                    1

[1022 rows x 1 columns]

In [35]:
pivot = scorecard_tn.groupby(['cip4','cred_desc']).size().unstack(fill_value=0)

valid_cips = pivot[
    (pivot["Bachelor's Degree"] > 0) &
    (pivot["Associate's Degree"] > 0) &
    (pivot["Undergraduate Certificate or Diploma"] > 0)
]

valid_cips.head(10)

cred_desc,Associate's Degree,Bachelor's Degree,Doctoral Degree,First Professional Degree,Graduate/Professional Certificate,Master's Degree,Post-baccalaureate Certificate,Undergraduate Certificate or Diploma
cip4,,,,,,,,
0100,1,4,1,0,0,1,0,1
0183,4,1,0,0,0,0,0,3
1002,3,5,0,0,0,2,0,5
1101,17,20,0,0,2,8,0,10
1102,1,1,0,0,0,0,0,1
1104,1,2,0,0,1,1,0,2
1108,7,7,0,0,1,1,0,6
1110,4,6,0,0,1,2,0,18
1205,6,1,0,0,1,0,0,8
1500,9,6,0,0,1,3,0,5

In [36]:
valid_cips.shape

(52, 8)

In [37]:
# Verify that scorecard and completions cip4 are the same.
scorecard_tn['cip4'].head(10)

0    2401
1    2401
2    2401
3    3802
4    3906
5    3906
6    3999
7    3999
8    3999
9    4400
Name: cip4, dtype: object

In [38]:
scorecard_tn = scorecard_tn[scorecard_tn["cip4"] != "99"]

In [39]:
scorecard_tn['cip4'].value_counts()

cip4
5202    134
5138    113
2401     85
5109     73
1312     68
       ...
0405      1
0406      1
0105      1
1106      1
5126      1
Name: count, Length: 292, dtype: int64

In [40]:
scorecard_tn["credlev"].value_counts().sort_index()

credlev
1     708
2     520
3    1685
4      15
5     718
6     222
7      62
8     236
Name: count, dtype: int64

In [41]:
scorecard_tn[['credlev', 'cred_desc']].drop_duplicates().sort_values('credlev')

     credlev                             cred_desc
3          1  Undergraduate Certificate or Diploma
0          2                    Associate's Degree
1          3                     Bachelor's Degree
2          4        Post-baccalaureate Certificate
8          5                       Master's Degree
35         6                       Doctoral Degree
110        7             First Professional Degree
30         8     Graduate/Professional Certificate

In [42]:
scorecard_tn = scorecard_tn[scorecard_tn["credlev"].isin([1, 2, 3])].copy()
scorecard_tn[["credlev", "cred_desc"]].value_counts()

credlev  cred_desc
3        Bachelor's Degree                       1685
1        Undergraduate Certificate or Diploma     708
2        Associate's Degree                       520
Name: count, dtype: int64

In [43]:
scorecard_tn.dtypes

unitid                        float64
inst_name                      object
cipcode                         int64
cip_desc                       object
credlev                         int64
cred_desc                      object
median_earnings_1yr            object
median_earnings_3yr            object
median_earnings_5yr            object
cip4                           object
state                          object
control                         int64
avg_annual_tuition_housing    float64
avg_annual_tuition            float64
avg_net_price_pub             float64
avg_net_price_priv            float64
dtype: object

In [44]:
scorecard_tn[["credlev", "cred_desc"]].value_counts().sort_index()

credlev  cred_desc
1        Undergraduate Certificate or Diploma     708
2        Associate's Degree                       520
3        Bachelor's Degree                       1685
Name: count, dtype: int64

In [45]:
desc_map = {
    "Undergraduate Certificate or Diploma" : "Certificate"
    ,"Associate's Degree" : "Associate"
    ,"Bachelor's Degree" : "Bachelor"
}
scorecard_tn["cred_desc"] = scorecard_tn["cred_desc"].map(desc_map)

In [46]:
# Convert dtypes to prepare for PBI
scorecard_tn["unitid"] = scorecard_tn["unitid"].astype(str)
scorecard_tn["cip4"] = scorecard_tn["cip4"].astype(str)
scorecard_tn["credlev"] = scorecard_tn["credlev"].astype(str)
scorecard_tn["control"] = scorecard_tn["control"].astype(str)

In [47]:
# Handle NaN and PS (Privacy Suppressed) values
cols_to_clean = ["median_earnings_1yr", "median_earnings_3yr", "median_earnings_5yr"]

for col in cols_to_clean:
    scorecard_tn[col] = (
        scorecard_tn[col]
            .replace("PS", np.nan)
            .replace({",": "", "\$": ""}, regex=True)
            .pipe(pd.to_numeric, errors="coerce")
            .astype("float64")
    )

In [48]:
scorecard_tn.dtypes

unitid                         object
inst_name                      object
cipcode                         int64
cip_desc                       object
credlev                        object
cred_desc                      object
median_earnings_1yr           float64
median_earnings_3yr           float64
median_earnings_5yr           float64
cip4                           object
state                          object
control                        object
avg_annual_tuition_housing    float64
avg_annual_tuition            float64
avg_net_price_pub             float64
avg_net_price_priv            float64
dtype: object

In [49]:
scorecard_tn.isna().mean().sort_values(ascending=False)

avg_annual_tuition            0.842430
median_earnings_3yr           0.765191
median_earnings_5yr           0.719533
median_earnings_1yr           0.713011
avg_net_price_pub             0.540680
avg_net_price_priv            0.466873
avg_annual_tuition_housing    0.165122
unitid                        0.000000
credlev                       0.000000
cred_desc                     0.000000
cipcode                       0.000000
cip_desc                      0.000000
inst_name                     0.000000
control                       0.000000
cip4                          0.000000
state                         0.000000
dtype: float64

In [50]:
scorecard_tn['unitid'].nunique()

132

In [51]:
scorecard_tn['cip4'].nunique()

263

In [52]:
# Drop columns before exporting to PBI.
scorecard_tn_export = scorecard_tn.drop(columns=["cipcode", "avg_annual_tuition"])
scorecard_tn_export.head(5)

,unitid,inst_name,cip_desc,credlev,cred_desc,median_earnings_1yr,median_earnings_3yr,median_earnings_5yr,cip4,state,control,avg_annual_tuition_housing,avg_net_price_pub,avg_net_price_priv
0,219505.0,American Baptist College,"Liberal Arts and Sciences, General Studies and...",2,Associate,NaN,NaN,NaN,2401,TN,2,27241.0,NaN,19294.0
1,219505.0,American Baptist College,"Liberal Arts and Sciences, General Studies and...",3,Bachelor,NaN,NaN,NaN,2401,TN,2,27241.0,NaN,19294.0
3,219505.0,American Baptist College,Religion/Religious Studies.,1,Certificate,NaN,NaN,NaN,3802,TN,2,27241.0,NaN,19294.0
4,219505.0,American Baptist College,Theological and Ministerial Studies.,1,Certificate,NaN,NaN,NaN,3906,TN,2,27241.0,NaN,19294.0
5,219505.0,American Baptist College,Theological and Ministerial Studies.,3,Bachelor,NaN,NaN,NaN,3906,TN,2,27241.0,NaN,19294.0

In [53]:
#####
def normalize_unitid(series):
    return series.astype(str).str.replace('.0','', regex=False).str.strip()

In [54]:
#####
scorecard_tn_export['unitid_n'] = (
    scorecard_tn_export['unitid']
    .astype(str)
    .str.replace('.0', '', regex=False)
    .str.strip()
)
# scorecard_tn_export = scorecard_tn_export   normalize_unitid(scorecard_tn_export['unitid'])

In [55]:
#####
scorecard_tn_export['cip4'] = (
    scorecard_tn_export['cip4']
        .astype(str)
        .str.replace('.', '', regex=False)
        .str.strip()
        .str[:4]
        .str.zfill(4)
)

In [56]:
#####
scorecard_tn_export['credlev_n'] = pd.to_numeric(
    scorecard_tn_export['credlev'], errors='coerce'
).astype('Int64')

In [57]:
#####
scorecard_tn_export['credlev_str'] = scorecard_tn_export['credlev_n'].astype(str)

In [58]:
scorecard_tn_export.head(1)

,unitid,inst_name,cip_desc,credlev,cred_desc,median_earnings_1yr,median_earnings_3yr,median_earnings_5yr,cip4,state,control,avg_annual_tuition_housing,avg_net_price_pub,avg_net_price_priv,unitid_n,credlev_n,credlev_str
0,219505.0,American Baptist College,"Liberal Arts and Sciences, General Studies and...",2,Associate,NaN,NaN,NaN,2401,TN,2,27241.0,NaN,19294.0,219505,2,2

In [59]:
#####
# Build composite key
scorecard_tn_export['composite_key'] = (
    scorecard_tn_export['unitid_n'] + "|" +
    scorecard_tn_export['cip4'] + "|" +
    scorecard_tn_export['credlev_str']
)

In [60]:
scorecard_tn_export.to_csv(
    "scorecard_tn_export.csv",
    index=False,
    encoding="utf-8"
)

scorecard_tn_export[scorecard_tn_export["inst_name"].str.contains("Middle Tennessee")][
    ["inst_name", "cip4", "cred_desc"]
].drop_duplicates().shape

dim_institution = (
    scorecard_tn_export[
    ["unitid_n", "inst_name", "state", "control"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_institution.to_csv("dim_institution.csv", index=False)

dim_program = (
    scorecard_tn_export[
        ["cip4", "cip_desc"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_program.to_csv("dim_program.csv", index=False)

dim_table = (
    scorecard_tn_export[
    ["unitid_n", "inst_name", "state", "control", "cip4", "cip_desc"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

# Build composite key
dim_table['composite_key'] = (
    scorecard_tn_export['unitid_n'] + "|" +
    scorecard_tn_export['cip4'] + "|" +
    scorecard_tn_export['credlev_str']
)

dim_table.to_csv("dim_table.csv", index=False)