In [1]:
import pandas as pd
import re

In [2]:
# Define columns needed and create dataframes from IPEDS 2011 and 2021
cols = ["UNITID", "CIPCODE", "AWLEVEL", "CTOTALT", "CTOTALM", "CTOTALW"]
c2011_clean = pd.read_csv(
    r"C:\capstone_data\raw\c2011_a.csv", 
    usecols=cols,
    dtype={"CIPCODE":str}
)

In [3]:
c2021_clean = pd.read_csv(
    r"C:\capstone_data\raw\c2021_a.csv", 
    usecols=cols,
    dtype={"CIPCODE":str}
)

In [4]:
# Dictionary for renaming columns
rename_dict = {
    "UNITID" : "unitid"
    ,"CIPCODE" : "cipcode"
    ,"AWLEVEL" : "credlev"
    ,"CTOTALT" : "completions"
    ,"CTOTALM" : "completions_men"
    ,"CTOTALW" : "completions_women"
}

In [5]:
# Rename the columns
c2011_clean = c2011_clean.rename(columns=rename_dict)
c2021_clean = c2021_clean.rename(columns=rename_dict)

In [6]:
print(c2011_clean.columns == c2021_clean.columns)

[ True  True  True  True  True  True]

In [7]:
# Set years
c2011_clean["year"] = 2011
c2021_clean["year"] = 2021

In [8]:
# "Stack" the two sets of data so that 2011 sits on top of 2021
completions = pd.concat([c2011_clean, c2021_clean], ignore_index=True)
completions.shape

(562151, 7)

In [9]:
c2011_clean["credlev"].value_counts().sort_index()
c2021_clean["credlev"].value_counts().sort_index()

credlev
2      30085
3      48506
4       2578
5     103820
6      12450
7      43913
8       5179
17     13130
18      2866
19       383
20      3762
21     29671
Name: count, dtype: int64

In [10]:
# Create a dictionary for the credlev codes, limiting it to the ones we are interested in
level_map = {
    2 : "Short Certificate"
    ,3 : "Long Certificate"
    ,5 : "Long Certificate"
    ,4 : "Associate"
    ,6 : "Bachelor"
}
completions["credential_group"] = completions["credlev"].map(level_map)

In [11]:
# Format ipeds cip code to xxxx dtype str format. Maintain cip code 99 for accuracy.
def ipeds_to_4digit(cip):
    s = str(cip)
    digits = "".join(re.findall(r"\d+", s))    # Extract the digits
    if digits == "99":
        return "9900"                         # Special: cip 99 to 9900
    digits = digits.zfill(6)
    return digits [:4]

completions["cip4"] = completions["cipcode"].apply(ipeds_to_4digit)

In [12]:
# Checkpoint to see if everything is looking good.
completions["year"].value_counts()

year
2021    296343
2011    265808
Name: count, dtype: int64

In [13]:
completions["credlev"].value_counts()

credlev
5     207121
3      96997
7      79758
2      59204
21     29671
1      25020
17     23747
6      17565
8       8312
4       5521
18      4794
20      3762
19       679
Name: count, dtype: int64

In [14]:
completions.head(8)

,unitid,cipcode,credlev,completions,completions_men,completions_women,year,credential_group,cip4
0,100636,09.0999,3,66,34,32,2011,Long Certificate,0909
1,100636,10.0105,3,547,398,149,2011,Long Certificate,1001
2,100636,11.0101,3,69,65,4,2011,Long Certificate,1101
3,100636,11.0401,3,915,705,210,2011,Long Certificate,1104
4,100636,13.0499,3,269,144,125,2011,Long Certificate,1304
5,100636,13.9999,3,1486,1244,242,2011,Long Certificate,1399
6,100636,13.9999,4,993,812,181,2011,Associate,1399
7,100636,15.0303,3,1012,913,99,2011,Long Certificate,1503

In [15]:
completions.tail(8)

,unitid,cipcode,credlev,completions,completions_men,completions_women,year,credential_group,cip4
562143,497329,51.0801,2,0,0,0,2021,Short Certificate,5108
562144,497329,51.3501,21,0,0,0,2021,NaN,5135
562145,497329,99,2,0,0,0,2021,Short Certificate,9900
562146,497329,99,21,0,0,0,2021,NaN,9900
562147,497338,51.0801,21,0,0,0,2021,NaN,5108
562148,497338,51.3801,3,0,0,0,2021,Long Certificate,5138
562149,497338,99,3,0,0,0,2021,Long Certificate,9900
562150,497338,99,21,0,0,0,2021,NaN,9900

In [16]:
completions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 562151 entries, 0 to 562150
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   unitid             562151 non-null  int64
 1   cipcode            562151 non-null  object
 2   credlev            562151 non-null  int64
 3   completions        562151 non-null  int64
 4   completions_men    562151 non-null  int64
 5   completions_women  562151 non-null  int64
 6   year               562151 non-null  int64
 7   credential_group   386408 non-null  object
 8   cip4               562151 non-null  object
dtypes: int64(6), object(3)
memory usage: 38.6+ MB

In [17]:
completions.dtypes

unitid                int64
cipcode              object
credlev               int64
completions           int64
completions_men       int64
completions_women     int64
year                  int64
credential_group     object
cip4                 object
dtype: object

In [18]:
completions["cip4"].unique()

array(['0909', '1001', '1101', '1104', '1304', '1399', '1503', '1504',
       '1505', '1506', '1507', '1510', '2203', '2609', '2902', '2904',
       '2999', '3106', '3199', '4004', '4199', '4301', '4302', '4303',
       '4407', '4706', '4901', '4999', '5006', '5009', '5106', '5107',
       '5108', '5109', '5110', '5115', '5118', '5122', '5131', '5199',
       '5202', '5203', '5210', '5401', '9900', '0100', '0101', '0109',
       '0110', '0111', '0199', '0305', '0403', '1002', '1310', '1312',
       '1313', '1408', '1410', '1419', '1499', '1502', '1508', '1901',
       '2301', '2401', '2601', '2701', '4005', '4008', '4201', '4228',
       '4506', '4510', '4511', '5007', '5102', '5208', '5214', '0502',
       '0901', '1301', '1311', '1401', '1405', '1409', '1414', '1418',
       '1601', '2602', '2604', '2605', '2608', '2610', '2611', '2613',
       '2615', '2703', '3019', '3099', '3105', '3801', '4404', '4502',
       '4599', '5001', '5005', '5104', '5105', '5112', '5117', '5123',
       '5138', '5206', '5212', '1199', '3902', '3906', '3907', '1108',
       '1110', '1314', '1407', '1435', '2313', '2612', '4099', '1107',
       '1305', '3103', '4499', '0301', '0501', '0904', '0907', '1306',
       '1402', '1411', '1420', '1433', '1605', '1609', '1904', '1907',
       '1909', '2201', '2202', '2501', '2705', '3000', '3802', '4006',
       '4507', '4509', '5003', '5004', '5209', '5213', '5216', '1204',
       '1513', '4701', '4702', '4805', '4807', '5139', '5201', '5204',
       '5219', '3018', '4501', '5299', '4001', '0103', '0306', '0402',
       '0404', '0405', '0406', '1403', '1404', '1428', '1432', '1445',
       '2607', '4504', '5120', '5124', '5125', '5211', '3008', '3010',
       '3020', '4399', '5111', '1512', '0106', '4703', '4799', '5215',
       '2299', '0999', '4601', '4602', '4603', '5135', '5218', '4102',
       '4605', '1205', '4803', '1105', '1109', '2399', '3904', '1905',
       '1906', '1599', '3101', '4103', '4704', '4902', '5126', '1203',
       '1500', '3001', '1003', '4604', '2903', '3023', '3905', '5010',
       '5100', '1612', '3899', '5099', '5207', '2699', '3011', '1303',
       '1511', '1616', '0112', '4010', '5220', '1509', '1102', '1501',
       '1515', '4400', '4402', '3903', '0302', '0303', '0399', '1315',
       '1421', '1425', '1439', '1603', '1610', '1699', '2603', '4002',
       '1099', '4903', '0410', '0910', '1309', '1413', '1516', '1604',
       '1611', '2200', '3013', '3014', '3015', '3033', '3800', '4405',
       '4512', '0409', '1106', '4600', '4699', '1302', '1412', '1427',
       '2614', '5114', '0102', '0105', '1103', '1436', '1442', '3017',
       '4299', '5127', '2503', '2314', '2799', '3012', '3016', '4101',
       '5217', '3005', '4227', '5136', '0108', '4899', '1514', '2599',
       '5133', '3999', '4503', '5002', '3025', '1423', '1437', '1613',
       '3022', '4505', '0107', '3027', '5101', '5119', '0499', '5221',
       '5205', '5132', '4513', '3030', '3028', '3006', '5121', '0408',
       '3032', '1443', '3026', '1999', '1422', '1307', '1606', '1424',
       '1438', '0104', '1299', '4800', '1902', '1614', '1607', '1406',
       '4808', '3031', '3021', '1434', '1608', '5134', '5137', '1441',
       '4700', '1900', '1444', '1440', '4100', '1615', '3029', '1602',
       '4514', '1447', '4304', '3070', '2706', '0180', '0183', '0181',
       '1448', '1517', '3038', '3046', '3052', '5011', '0113', '0599',
       '3047', '3051', '3071', '1617', '3044', '3045', '3041', '3908',
       '3039', '4707', '0182', '4011', '1206', '3035', '3036', '1910',
       '3049', '3043', '3053', '3048', '2906', '3034'], dtype=object)