In [1]:
import pandas as pd

In [2]:
# completions_export = pd.read_csv("..\data\completions_export.csv")
completions_cip4_agg = pd.read_csv("..\data\completions_cip4_agg.csv")
scorecard_tn_export = pd.read_csv("..\data\scorecard_tn_export.csv")

In [4]:
# Create a list of unitids for each dataset
scorecard_unitids = set(scorecard_tn_export['unitid_n'])
completions_unitids = set(completions_cip4_agg['unitid_n'])

In [10]:
# Define match, scorecard_only, and completions_only
matching_unitids = scorecard_unitids & completions_unitids
scorecard_only = scorecard_unitids - completions_unitids
completions_only = completions_unitids - scorecard_unitids

In [11]:
# Create a df for the cross filter
unitid_cross = pd.DataFrame({
    'unitid_n' : list(scorecard_unitids | completions_unitids)
})

In [12]:
# Create column with .isin data
unitid_cross['in_scorecard'] = unitid_cross['unitid_n'].isin(scorecard_unitids)
unitid_cross['in_completions'] = unitid_cross['unitid_n'].isin(completions_unitids)
unitid_cross['match'] = unitid_cross['in_scorecard'] & unitid_cross['in_completions']

In [13]:
# Sort matches
unitid_cross = unitid_cross.sort_values(['match', 'unitid_n'], ascending=[False, True])
unitid_cross.head(20)

      unitid_n  in_scorecard  in_completions  match
3236    219505          True            True   True
3263    219587          True            True   True
3267    219596          True            True   True
3273    219602          True            True   True
3288    219639          True            True   True
3320    219709          True            True   True
3324    219718          True            True   True
3351    219790          True            True   True
3358    219806          True            True   True
3368    219824          True            True   True
3374    219833          True            True   True
3379    219842          True            True   True
3385    219851          True            True   True
3403    219879          True            True   True
3407    219888          True            True   True
3413    219903          True            True   True
3434    219949          True            True   True
3446    219976          True            True   True
3453    219994          True            True   True
3486    220057          True            True   True

In [20]:
# Examine False results
matching_unitids_df = unitid_cross[unitid_cross['match'] == False]
matching_unitids_df.head(20)

      unitid_n  in_scorecard  in_completions  match
1115    100636         False            True  False
1127    100654         False            True  False
1129    100663         False            True  False
1138    100690         False            True  False
1148    100706         False            True  False
1160    100724         False            True  False
1177    100751         False            True  False
1183    100760         False            True  False
1211    100812         False            True  False
1217    100830         False            True  False
1227    100858         False            True  False
1263    100937         False            True  False
1310    101028         False            True  False
1329    101073         False            True  False
1351    101116         False            True  False
1365    101143         False            True  False
1378    101161         False            True  False
1396    101189         False            True  False
1422    101240         False            True  False
1444    101277         False            True  False

In [21]:
# How many unitids are in both?
unitid_cross['match'].value_counts()

match
False    7722
True      129
Name: count, dtype: int64

In [24]:
# How many unitids are in TN?
scorecard_tn_export['unitid_n'].nunique()

132

In [25]:
# Test composite_keys to ensure the overlap is as expected.
scorecard_keys = set(scorecard_tn_export['composite_key'])
completions_keys = set(completions_cip4_agg['composite_key'])

In [26]:
matching_keys = scorecard_keys & completions_keys
print("Number of composite keys in both tables:", len(matching_keys))

Number of composite keys in both tables: 586

In [28]:
scorecard_only_keys = scorecard_keys - completions_keys
print("Composite keys in Scorecard but NOT in Completions:", len(scorecard_only_keys))

Composite keys in Scorecard but NOT in Completions: 2327

In [30]:
completions_only_keys = completions_keys - scorecard_keys
print("Composite keys in Completions but NOT in Scorecard:", len(completions_only_keys))

Composite keys in Completions but NOT in Scorecard: 137834