In [1]:
import pandas as pd
import numpy as np

In [4]:
# completions_export = pd.read_csv("..\data\completions_export.csv")
completions_join = pd.read_csv("..\data\completions_fact_2024.csv")
scorecard_tn_join = pd.read_csv("..\data\scorecard_fact_2024.csv")

In [5]:
completions_join.head()

,completions,completions_men,completions_women,unitid_n,cip4,credlev_n,year,credlev_proj,cred_desc,composite_key
0,12,2,10,100654,109,5,2024,3,Bachelor,100654|0109|3
1,10,1,9,100654,110,5,2024,3,Bachelor,100654|0110|3
2,2,1,1,100654,199,5,2024,3,Bachelor,100654|0199|3
3,0,0,0,100654,305,5,2024,3,Bachelor,100654|0305|3
4,8,1,7,100654,403,5,2024,3,Bachelor,100654|0403|3

In [6]:
completions_join.dtypes

completions           int64
completions_men       int64
completions_women     int64
unitid_n              int64
cip4                  int64
credlev_n             int64
year                  int64
credlev_proj          int64
cred_desc            object
composite_key        object
dtype: object

In [10]:
completions_join["unitid_n"].nunique()

5468

In [7]:
scorecard_tn_join.head()

,unitid,inst_name,cip_desc,credlev,cred_desc,median_earnings_1yr,median_earnings_3yr,median_earnings_5yr,cip4,state,control,avg_annual_tuition_housing,avg_net_price_pub,avg_net_price_priv,unitid_n,credlev_n,credlev_str,composite_key
0,219505.0,American Baptist College,"Liberal Arts and Sciences, General Studies and...",2,Associate,NaN,NaN,NaN,2401,TN,2,27241.0,NaN,19294.0,219505,2,2,219505|2401|2
1,219505.0,American Baptist College,"Liberal Arts and Sciences, General Studies and...",3,Bachelor,NaN,NaN,NaN,2401,TN,2,27241.0,NaN,19294.0,219505,3,3,219505|2401|3
2,219505.0,American Baptist College,Religion/Religious Studies.,1,Certificate,NaN,NaN,NaN,3802,TN,2,27241.0,NaN,19294.0,219505,1,1,219505|3802|1
3,219505.0,American Baptist College,Theological and Ministerial Studies.,1,Certificate,NaN,NaN,NaN,3906,TN,2,27241.0,NaN,19294.0,219505,1,1,219505|3906|1
4,219505.0,American Baptist College,Theological and Ministerial Studies.,3,Bachelor,NaN,NaN,NaN,3906,TN,2,27241.0,NaN,19294.0,219505,3,3,219505|3906|3

In [9]:
scorecard_tn_join.dtypes

unitid                        float64
inst_name                      object
cip_desc                       object
credlev                         int64
cred_desc                      object
median_earnings_1yr           float64
median_earnings_3yr           float64
median_earnings_5yr           float64
cip4                            int64
state                          object
control                         int64
avg_annual_tuition_housing    float64
avg_net_price_pub             float64
avg_net_price_priv            float64
unitid_n                        int64
credlev_n                       int64
credlev_str                     int64
composite_key                  object
dtype: object

In [11]:
scorecard_tn_join["unitid_n"].nunique()

132

In [14]:
overlap = set(scorecard_tn_join["unitid_n"]) & set(completions_join["unitid_n"])
len(overlap)

129

In [15]:
tn_unitids = scorecard_tn_join["unitid_n"].unique()

completions_tn = completions_join[completions_join["unitid_n"].isin(tn_unitids)]
len(completions_tn)

4101

In [18]:
completions_tn["unitid_n"].nunique()

129

In [22]:
completions_tn.head(3)

,completions,completions_men,completions_women,unitid_n,cip4,credlev_n,year,credlev_proj,cred_desc,composite_key
137863,1,0,1,219505,2401,3,2024,2,Assoicate,219505|2401|2
137864,5,4,1,219505,3999,5,2024,3,Bachelor,219505|3999|3
137865,0,0,0,219505,4400,5,2024,3,Bachelor,219505|4400|3

In [26]:
completions_tn["composite_key"].nunique()

2898

In [27]:
scorecard_tn_join["composite_key"].nunique()

2913

In [23]:
overlap = set(completions_tn["composite_key"]) & set(scorecard_tn_join["composite_key"])

len(overlap)

2208

In [28]:
merged = completions_tn.merge(
    scorecard_tn_join,
    on="composite_key",
    how="left"
)

In [29]:
merged.shape

(4101, 27)

In [31]:
merged["composite_key"].nunique()

2898

In [32]:
merged.to_csv(
    "tn_data.csv",
    index=False,
    encoding="utf-8"
)